services:
  db:
    image: postgres:17-alpine
    container_name: zorgwerkwijzer-db
    environment:
      POSTGRES_DB: zorgwerkwijzer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: zorgwerkwijzer-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zorgwerkwijzer.nl
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
