-- V14: Admin Audit Log
-- Immutable log van alle admin-mutaties.
-- Geen foreign keys — records moeten blijven bestaan ook als het gerelateerde object verwijderd is.

CREATE TABLE admin_audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id  BIGINT        NOT NULL,
    admin_email    VARCHAR(255)  NOT NULL,
    action         VARCHAR(100)  NOT NULL,
    entity_type    VARCHAR(50)   NOT NULL,
    entity_id      BIGINT,
    entity_name    VARCHAR(255),
    old_value      TEXT,
    new_value      TEXT,
    created_at     TIMESTAMP     NOT NULL DEFAULT NOW()
);

-- Filters op wie de actie uitvoerde
CREATE INDEX idx_audit_admin_user_id ON admin_audit_log(admin_user_id);

-- Filters op type actie
CREATE INDEX idx_audit_action ON admin_audit_log(action);

-- Filters op object (entity_type + entity_id samengesteld)
CREATE INDEX idx_audit_entity ON admin_audit_log(entity_type, entity_id);

-- Tijdlijn queries (meest gebruikt — nieuwste eerst)
CREATE INDEX idx_audit_created_at ON admin_audit_log(created_at DESC);

-- Gecombineerde filter: admin X in periode Y
CREATE INDEX idx_audit_admin_created ON admin_audit_log(admin_user_id, created_at DESC);
