-- V15: Stripe Subscription tabellen
-- subscription_packages: pakket-definities (STARTER / PROFESSIONAL / PREMIUM)
-- employer_subscriptions: actieve abonnementen per werkgever (UNIQUE per werkgever)
-- stripe_webhook_events:  idempotency-log voor inkomende Stripe webhook events

-- ─── subscription_packages ──────────────────────────────────────────────────
CREATE TABLE subscription_packages (
    id                      BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(50)   NOT NULL,
    display_name            VARCHAR(100)  NOT NULL,
    price_monthly_cents     INTEGER       NOT NULL,
    price_yearly_cents      INTEGER       NOT NULL,
    stripe_price_id_monthly VARCHAR(100),
    stripe_price_id_yearly  VARCHAR(100),
    max_active_vacancies    INTEGER,
    can_view_cv             BOOLEAN       NOT NULL DEFAULT FALSE,
    can_see_applicant_contact BOOLEAN     NOT NULL DEFAULT FALSE,
    is_featured_included    BOOLEAN       NOT NULL DEFAULT FALSE,
    is_active               BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_subscription_packages_name UNIQUE (name)
);

CREATE INDEX idx_subscription_packages_name     ON subscription_packages(name);
CREATE INDEX idx_subscription_packages_is_active ON subscription_packages(is_active);

-- Seed data: 3 pakketten
-- Stripe Price IDs worden na Stripe Dashboard setup ingevuld via admin-panel
INSERT INTO subscription_packages
    (name, display_name, price_monthly_cents, price_yearly_cents,
     max_active_vacancies, can_view_cv, can_see_applicant_contact, is_featured_included)
VALUES
    ('STARTER',      'Starter',      4900,  47040, 3,    FALSE, FALSE, FALSE),
    ('PROFESSIONAL', 'Professional', 9900,  95040, 10,   TRUE,  TRUE,  FALSE),
    ('PREMIUM',      'Premium',      19900, 191040, NULL, TRUE,  TRUE,  TRUE);


-- ─── employer_subscriptions ──────────────────────────────────────────────────
-- UNIQUE(employer_id): één actief abonnement per werkgever — database-level garantie.
-- Geen circulaire FK: employers heeft GEEN subscription_id kolom.
-- Navigatie loopt uitsluitend via employer_subscriptions.employer_id.
CREATE TABLE employer_subscriptions (
    id                       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employer_id              BIGINT       NOT NULL,
    package_id               BIGINT       NOT NULL,
    stripe_customer_id       VARCHAR(100),
    stripe_subscription_id   VARCHAR(100),
    status                   VARCHAR(50)  NOT NULL DEFAULT 'INACTIVE',
    billing_interval         VARCHAR(20)  NOT NULL DEFAULT 'MONTHLY',
    current_period_start     TIMESTAMP,
    current_period_end       TIMESTAMP,
    trial_end                TIMESTAMP,
    canceled_at              TIMESTAMP,
    created_at               TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_employer_subscriptions_employer_id      UNIQUE (employer_id),
    CONSTRAINT uq_employer_subscriptions_stripe_sub_id    UNIQUE (stripe_subscription_id),
    CONSTRAINT uq_employer_subscriptions_stripe_cust_id   UNIQUE (stripe_customer_id),
    CONSTRAINT fk_employer_subscriptions_employer         FOREIGN KEY (employer_id)  REFERENCES employers(id)              ON DELETE CASCADE,
    CONSTRAINT fk_employer_subscriptions_package          FOREIGN KEY (package_id)   REFERENCES subscription_packages(id)  ON DELETE RESTRICT
);

CREATE INDEX idx_employer_subscriptions_employer_id       ON employer_subscriptions(employer_id);
CREATE INDEX idx_employer_subscriptions_stripe_sub_id     ON employer_subscriptions(stripe_subscription_id);
CREATE INDEX idx_employer_subscriptions_stripe_cust_id    ON employer_subscriptions(stripe_customer_id);
CREATE INDEX idx_employer_subscriptions_status            ON employer_subscriptions(status);


-- ─── stripe_webhook_events ───────────────────────────────────────────────────
-- Idempotency-log: UNIQUE(stripe_event_id) vangt dubbele webhook delivery op
-- database-niveau op, ook bij een race condition in de applicatielaag.
CREATE TABLE stripe_webhook_events (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stripe_event_id VARCHAR(100)  NOT NULL,
    event_type      VARCHAR(100)  NOT NULL,
    processed       BOOLEAN       NOT NULL DEFAULT FALSE,
    processed_at    TIMESTAMP,
    payload         TEXT,
    created_at      TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_stripe_webhook_events_event_id UNIQUE (stripe_event_id)
);

CREATE INDEX idx_stripe_webhook_event_id   ON stripe_webhook_events(stripe_event_id);
CREATE INDEX idx_stripe_webhook_created_at ON stripe_webhook_events(created_at DESC);
