-- V16: Password Reset Tokens
-- Stores one-time tokens for password reset functionality.
-- Tokens are single-use and expire after 1 hour.

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL,
    token       VARCHAR(64)  NOT NULL,
    expires_at  TIMESTAMP    NOT NULL,
    used        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_password_reset_token UNIQUE (token)
);

CREATE INDEX idx_password_reset_email     ON password_reset_tokens(email);
CREATE INDEX idx_password_reset_token     ON password_reset_tokens(token);
CREATE INDEX idx_password_reset_expires   ON password_reset_tokens(expires_at);
