CREATE TABLE employers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)  NOT NULL,
    slug        VARCHAR(255)  NOT NULL UNIQUE,
    email       VARCHAR(255)  NOT NULL UNIQUE,
    phone_number VARCHAR(50),
    address     VARCHAR(500),
    logo_url    TEXT,
    website_url TEXT,
    description TEXT,
    is_premium  BOOLEAN       NOT NULL DEFAULT FALSE,
    seo_title   VARCHAR(255),
    seo_description TEXT,
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL
);

CREATE INDEX idx_employers_slug      ON employers(slug);
CREATE INDEX idx_employers_email     ON employers(email);
CREATE INDEX idx_employers_is_premium ON employers(is_premium);
