CREATE TABLE vacancies (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employer_id      BIGINT        NOT NULL REFERENCES employers(id) ON DELETE CASCADE,
    city_id          BIGINT,
    occupation_id    BIGINT,
    title            VARCHAR(255)  NOT NULL,
    slug             VARCHAR(300)  NOT NULL UNIQUE,
    description      TEXT          NOT NULL,
    requirements     TEXT,
    salary_min       NUMERIC(10,2),
    salary_max       NUMERIC(10,2),
    hours_min        INTEGER,
    hours_max        INTEGER,
    employment_type  VARCHAR(50),
    education_level  VARCHAR(50),
    is_active        BOOLEAN       NOT NULL DEFAULT TRUE,
    published_at     TIMESTAMP     NOT NULL DEFAULT NOW(),
    expires_at       TIMESTAMP,
    seo_title        VARCHAR(255),
    seo_description  TEXT,
    created_at       TIMESTAMP     NOT NULL,
    updated_at       TIMESTAMP     NOT NULL
);

CREATE UNIQUE INDEX idx_vacancies_slug            ON vacancies(slug);
CREATE INDEX idx_vacancies_employer_id            ON vacancies(employer_id);
CREATE INDEX idx_vacancies_city_id                ON vacancies(city_id);
CREATE INDEX idx_vacancies_occupation_id          ON vacancies(occupation_id);
CREATE INDEX idx_vacancies_is_active              ON vacancies(is_active);
CREATE INDEX idx_vacancies_published_at           ON vacancies(published_at DESC);
CREATE INDEX idx_vacancies_active_published       ON vacancies(is_active, published_at DESC);
CREATE INDEX idx_vacancies_employment_type        ON vacancies(employment_type);
CREATE INDEX idx_vacancies_education_level        ON vacancies(education_level);
