CREATE TABLE news_articles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(255)              NOT NULL,
    slug          VARCHAR(300)              NOT NULL UNIQUE,
    content       TEXT                      NOT NULL,
    excerpt       TEXT,
    category      VARCHAR(100),
    author        VARCHAR(255),
    featured_image_url TEXT,
    is_published  BOOLEAN                   NOT NULL DEFAULT FALSE,
    published_at  TIMESTAMP,
    meta_title    VARCHAR(255),
    meta_description TEXT,
    created_at    TIMESTAMP                 NOT NULL,
    updated_at    TIMESTAMP                 NOT NULL
);

CREATE INDEX idx_news_articles_slug        ON news_articles (slug);
CREATE INDEX idx_news_articles_published   ON news_articles (is_published, published_at DESC);
CREATE INDEX idx_news_articles_category    ON news_articles (category);
