CREATE TABLE profiles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(100)  NOT NULL,
    last_name   VARCHAR(100)  NOT NULL,
    email       VARCHAR(255)  NOT NULL,
    phone_number VARCHAR(50),
    cv_url      TEXT,
    current_occupation_id BIGINT,
    is_searching BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_profiles_email UNIQUE (email)
);

CREATE INDEX idx_profiles_email ON profiles (email);
