CREATE TABLE applications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id   BIGINT       NOT NULL,
    profile_id   BIGINT       NOT NULL,
    status       VARCHAR(50)  NOT NULL DEFAULT 'NEW',
    cover_letter TEXT,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_applications_vacancy FOREIGN KEY (vacancy_id) REFERENCES vacancies (id) ON DELETE RESTRICT,
    CONSTRAINT fk_applications_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE,
    CONSTRAINT uq_applications_vacancy_profile UNIQUE (vacancy_id, profile_id)
);

CREATE INDEX idx_applications_vacancy_id ON applications (vacancy_id);
CREATE INDEX idx_applications_profile_id ON applications (profile_id);
CREATE INDEX idx_applications_status     ON applications (status);
