CREATE TABLE saved_jobs (
    id         BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id BIGINT    NOT NULL,
    profile_id BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_saved_jobs_vacancy FOREIGN KEY (vacancy_id) REFERENCES vacancies (id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_jobs_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE,
    CONSTRAINT uq_saved_jobs_vacancy_profile UNIQUE (vacancy_id, profile_id)
);

CREATE INDEX idx_saved_jobs_profile_id ON saved_jobs (profile_id);
CREATE INDEX idx_saved_jobs_vacancy_id ON saved_jobs (vacancy_id);
