-- V9: Create users table for JWT authentication
-- Role is always set server-side; never accepted from client input (C1 fix)

CREATE TABLE users
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                 VARCHAR(255)        NOT NULL,
    password              VARCHAR(255)        NOT NULL,
    role                  VARCHAR(50)         NOT NULL DEFAULT 'ROLE_USER',
    employer_id           BIGINT,
    failed_login_attempts INTEGER             NOT NULL DEFAULT 0,
    locked_until          TIMESTAMP,
    created_at            TIMESTAMP           NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP           NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('ROLE_USER', 'ROLE_EMPLOYER', 'ROLE_ADMIN'))
);

CREATE INDEX idx_users_email ON users (email);
